### ISSUE TITLE
Feature Request: Sell equippable items below certain ilvl

### ISSUE THREAD

**Issue by DiscordGregory** [DrOxlotus/BagCleaner#3]
If you don't want to go through the trouble of adding whole raids worth of items to your DB you can set items under a certain item level that can be equipped to be sold automatically. You'll need a way to add items to be excluded though for cases like fishing poles/hats/cosmetics and gear to be upgraded at a later date like the ICC class gear.

**Comment by DrOxlotus** [comment]
#2 will be implemented at some point in the future. Closing.
